#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MAIN="$ROOT/src/main.rs"
DSP="$ROOT/src/software_dsp.rs"
PROFILE="$ROOT/src/profile.rs"
LIB="$ROOT/src/lib.rs"
grep -Fq 'pub mod software_dsp;' "$LIB"
grep -Fq 'HEADPHONE_EQ_BAND_COUNT: usize = 10' "$DSP"
grep -Fq 'pub struct SoftwareDspState' "$DSP"
grep -Fq 'pub enum DspBackendState' "$DSP"
grep -Fq 'Unavailable' "$DSP"
grep -Fq 'pub de_esser:' "$DSP"
grep -Fq 'pub exciter:' "$DSP"
grep -Fq 'pub binaural_personalization:' "$DSP"
grep -Fq 'pub fn save_snapshot' "$PROFILE"
grep -Fq 'pub fn list_snapshots' "$PROFILE"
grep -Fq 'De-Esser' "$MAIN"
grep -Fq 'Exciter' "$MAIN"
grep -Fq 'Snapshot' "$MAIN"
grep -Fq 'DSP Backend' "$MAIN"
grep -Fq 'SYSTEM AUDIO PROTECTED' "$MAIN"
! grep -Fq 'HardwareController::connect()' "$MAIN"
echo 'AETHERFORGE_BEACN_V0_1_12_WINDOWS_LIVE_DSP_CONTRACT=PASS'
