[package]
name = "aether-retrieval"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aether-workspace = { path = "../aether-workspace" }
serde_json.workspace = true
aether-core = { path = "../aether-core" }
aether-storage = { path = "../aether-storage" }
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true

async-trait.workspace = true

aether-index = { path = "../aether-index" }

[dev-dependencies]

tokio.workspace = true
