[package]
name = "aether-index"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]

aether-core = { path = "../aether-core" }
aether-storage = { path = "../aether-storage" }
chrono.workspace = true
thiserror.workspace = true
uuid.workspace = true

serde.workspace = true

aether-tools = { path = "../aether-tools" }
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
