//! Read-only BEACN Mic onboard-profile import.
//!
//! The transport is provided by the MIT-licensed `beacn-lib` project. This module
//! only issues generated fetch/get messages. It never sends setter messages and
//! never writes to the microphone's onboard storage.

use crate::hardware::{EqBandKind, HeadphonePower, NoiseStyle, ProcessorMode};
use crate::profile::{self, Profile};
use crate::software_dsp::SoftwareDspState;
use beacn_lib::MaybeFuture;
use beacn_lib::audio::messages::Message;
use beacn_lib::audio::messages::compressor::{Compressor, CompressorMode};
use beacn_lib::audio::messages::controls::Controls;
use beacn_lib::audio::messages::deesser::DeEsser;
use beacn_lib::audio::messages::eq_common::{EQBand, EQBandType};
use beacn_lib::audio::messages::eq_headphones::{EQChannel, EQHeadphones};
use beacn_lib::audio::messages::eq_microphone::{EQMicrophone, EQMode};
use beacn_lib::audio::messages::exciter::Exciter;
use beacn_lib::audio::messages::expander::{Expander, ExpanderMode};
use beacn_lib::audio::messages::headphones::{HeadphoneTypes, Headphones};
use beacn_lib::audio::messages::mic_setup::MicSetup;
use beacn_lib::audio::messages::suppressor::{Suppressor, SuppressorStyle};
use beacn_lib::audio::{BeacnAudioDevice, open_audio_device};
use beacn_lib::manager::{DeviceType, get_beacn_mic_devices};
use beacn_lib::types::ToInner;
use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

pub const ON_DEVICE_PROFILE_NAME: &str = "On Device";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SnapshotOrigin {
    Device,
    Cache,
}

impl SnapshotOrigin {
    pub const fn label(self) -> &'static str {
        match self {
            Self::Device => "MIC MEMORY",
            Self::Cache => "CACHE FALLBACK",
        }
    }
}

#[derive(Debug, Clone)]
pub struct OnDeviceSnapshot {
    pub serial: String,
    pub firmware: String,
    pub dsp: SoftwareDspState,
    pub imported_messages: usize,
    pub failed_messages: usize,
    pub origin: SnapshotOrigin,
}

impl OnDeviceSnapshot {
    pub fn summary(&self) -> String {
        format!(
            "{} · {} settings read · {} unavailable",
            self.origin.label(),
            self.imported_messages,
            self.failed_messages
        )
    }
}

/// Read the current stored BEACN Mic parameters. Every request produced here is
/// a getter generated by `Message::generate_fetch_message`; responses are only
/// decoded into the local profile model.
pub fn scan(target_serial: Option<&str>) -> Result<OnDeviceSnapshot, String> {
    let locations = get_beacn_mic_devices().wait();
    if locations.is_empty() {
        return Err("no BEACN Mic was discovered by beacn-lib".to_owned());
    }

    let target_serial = target_serial.filter(|value| !value.trim().is_empty());
    let mut selected: Option<Box<dyn BeacnAudioDevice>> = None;
    let mut fallback: Option<Box<dyn BeacnAudioDevice>> = None;
    let mut opened_count = 0usize;
    let mut open_errors = Vec::new();

    for location in locations {
        match open_audio_device(location).wait() {
            Ok(device) => {
                opened_count += 1;
                let serial = device.get_serial();
                if target_serial.is_none_or(|value| serial_matches(&serial, value)) {
                    selected = Some(device);
                    break;
                }
                if fallback.is_none() {
                    fallback = Some(device);
                }
            }
            Err(error) => open_errors.push(error.to_string()),
        }
    }

    if selected.is_none() && opened_count == 1 {
        selected = fallback;
    }

    let Some(device) = selected else {
        let suffix = if open_errors.is_empty() {
            String::new()
        } else {
            format!(": {}", open_errors.join("; "))
        };
        return Err(format!("BEACN Mic could not be opened read-only{suffix}"));
    };

    let serial = device.get_serial();
    let version = device.get_version();
    let firmware = version.to_string();
    let requests = Message::generate_fetch_message(DeviceType::BeacnMic, version);

    let mut dsp = SoftwareDspState::default();
    let mut imported_messages = 0usize;
    let mut failed_messages = 0usize;

    for request in requests {
        match device.handle_message(request).wait() {
            Ok(response) => {
                if apply_response(&mut dsp, response) {
                    imported_messages += 1;
                }
            }
            Err(_) => failed_messages += 1,
        }
    }

    // A valid import must include more than one isolated property. This avoids
    // presenting a mostly-default local model as though it came from the mic.
    if imported_messages < 3 {
        return Err(format!(
            "BEACN Mic responded, but only {imported_messages} supported settings were decoded"
        ));
    }

    dsp.sanitize();
    Ok(OnDeviceSnapshot {
        serial,
        firmware,
        dsp,
        imported_messages,
        failed_messages,
        origin: SnapshotOrigin::Device,
    })
}

pub fn scan_with_cache_fallback(target_serial: Option<&str>) -> Result<OnDeviceSnapshot, String> {
    match scan(target_serial) {
        Ok(snapshot) => {
            if let Err(error) = save_cache(&snapshot) {
                eprintln!("AETHERFORGE_BEACN_ON_DEVICE_CACHE_SAVE=FAIL:{error}");
            }
            Ok(snapshot)
        }
        Err(scan_error) => match load_cache(target_serial) {
            Ok(mut cached) => {
                cached.origin = SnapshotOrigin::Cache;
                Ok(cached)
            }
            Err(cache_error) => Err(format!(
                "on-device read failed: {scan_error}; cache unavailable: {cache_error}"
            )),
        },
    }
}

pub fn save_cache(snapshot: &OnDeviceSnapshot) -> io::Result<PathBuf> {
    let dir = cache_dir()?;
    fs::create_dir_all(&dir)?;
    let path = dir.join(format!("{}.profile", safe_serial(&snapshot.serial)));
    let item = Profile {
        name: ON_DEVICE_PROFILE_NAME.to_owned(),
        source_name: String::new(),
        source_volume: 0.0,
        source_muted: false,
        sink_name: String::new(),
        sink_volume: 0.0,
        sink_muted: false,
        dsp: snapshot.dsp.clone(),
    };
    let mut text = profile::encode(&item);
    text.push_str(&format!(
        "on_device.serial={}\n",
        clean_meta(&snapshot.serial)
    ));
    text.push_str(&format!(
        "on_device.firmware={}\n",
        clean_meta(&snapshot.firmware)
    ));
    text.push_str(&format!(
        "on_device.imported_messages={}\n",
        snapshot.imported_messages
    ));
    text.push_str(&format!(
        "on_device.failed_messages={}\n",
        snapshot.failed_messages
    ));
    atomic_write(&path, &text)?;
    Ok(path)
}

pub fn load_cache(target_serial: Option<&str>) -> io::Result<OnDeviceSnapshot> {
    let dir = cache_dir()?;
    let path = match target_serial.filter(|value| !value.trim().is_empty()) {
        Some(serial) => dir.join(format!("{}.profile", safe_serial(serial))),
        None => newest_profile(&dir)?,
    };
    let text = fs::read_to_string(path)?;
    let item = profile::decode(&text)?;
    Ok(OnDeviceSnapshot {
        serial: meta_field(&text, "on_device.serial").unwrap_or_default(),
        firmware: meta_field(&text, "on_device.firmware").unwrap_or_else(|| "unknown".to_owned()),
        dsp: item.dsp,
        imported_messages: meta_field(&text, "on_device.imported_messages")
            .and_then(|value| value.parse().ok())
            .unwrap_or_default(),
        failed_messages: meta_field(&text, "on_device.failed_messages")
            .and_then(|value| value.parse().ok())
            .unwrap_or_default(),
        origin: SnapshotOrigin::Cache,
    })
}

fn apply_response(dsp: &mut SoftwareDspState, response: Message) -> bool {
    match response {
        Message::MicSetup(MicSetup::MicGain(value)) => {
            dsp.mic_gain_db = value.to_inner() as f32;
        }
        Message::EQMicrophone(EQMicrophone::Mode(mode)) => {
            dsp.mic_eq_mode = processor_mode_from_eq(mode);
        }
        Message::EQMicrophone(EQMicrophone::Type(mode, band, value)) => {
            if processor_mode_from_eq(mode) == dsp.mic_eq_mode {
                let index = eq_index(band);
                if let Some(slot) = dsp.mic_eq.get_mut(index) {
                    slot.kind = eq_kind(value);
                }
            }
        }
        Message::EQMicrophone(EQMicrophone::Gain(mode, band, value)) => {
            if processor_mode_from_eq(mode) == dsp.mic_eq_mode {
                if let Some(slot) = dsp.mic_eq.get_mut(eq_index(band)) {
                    slot.gain_db = value.to_inner();
                }
            }
        }
        Message::EQMicrophone(EQMicrophone::Frequency(mode, band, value)) => {
            if processor_mode_from_eq(mode) == dsp.mic_eq_mode {
                if let Some(slot) = dsp.mic_eq.get_mut(eq_index(band)) {
                    slot.frequency_hz = value.to_inner();
                }
            }
        }
        Message::EQMicrophone(EQMicrophone::Q(mode, band, value)) => {
            if processor_mode_from_eq(mode) == dsp.mic_eq_mode {
                if let Some(slot) = dsp.mic_eq.get_mut(eq_index(band)) {
                    slot.q = value.to_inner();
                }
            }
        }
        Message::EQMicrophone(EQMicrophone::Enabled(mode, band, value)) => {
            if processor_mode_from_eq(mode) == dsp.mic_eq_mode {
                if let Some(slot) = dsp.mic_eq.get_mut(eq_index(band)) {
                    slot.enabled = value;
                }
            }
        }
        Message::Compressor(Compressor::Mode(mode)) => {
            dsp.compressor.mode = processor_mode_from_compressor(mode);
        }
        Message::Compressor(Compressor::Attack(mode, value)) => {
            if processor_mode_from_compressor(mode) == dsp.compressor.mode {
                dsp.compressor.attack_ms = value.to_inner();
            }
        }
        Message::Compressor(Compressor::Release(mode, value)) => {
            if processor_mode_from_compressor(mode) == dsp.compressor.mode {
                dsp.compressor.release_ms = value.to_inner();
            }
        }
        Message::Compressor(Compressor::Threshold(mode, value)) => {
            if processor_mode_from_compressor(mode) == dsp.compressor.mode {
                dsp.compressor.threshold_db = value.to_inner();
            }
        }
        Message::Compressor(Compressor::Ratio(mode, value)) => {
            if processor_mode_from_compressor(mode) == dsp.compressor.mode {
                dsp.compressor.ratio = value.to_inner();
            }
        }
        Message::Compressor(Compressor::MakeupGain(mode, value)) => {
            if processor_mode_from_compressor(mode) == dsp.compressor.mode {
                dsp.compressor.makeup_gain_db = value.to_inner();
            }
        }
        Message::Compressor(Compressor::Enabled(mode, value)) => {
            if processor_mode_from_compressor(mode) == dsp.compressor.mode {
                dsp.compressor.enabled = value;
            }
        }
        Message::Expander(Expander::Mode(mode)) => {
            dsp.expander.mode = processor_mode_from_expander(mode);
        }
        Message::Expander(Expander::Threshold(mode, value)) => {
            if processor_mode_from_expander(mode) == dsp.expander.mode {
                dsp.expander.threshold_db = value.to_inner();
            }
        }
        Message::Expander(Expander::Ratio(mode, value)) => {
            if processor_mode_from_expander(mode) == dsp.expander.mode {
                dsp.expander.ratio = value.to_inner();
            }
        }
        Message::Expander(Expander::Enabled(mode, value)) => {
            if processor_mode_from_expander(mode) == dsp.expander.mode {
                dsp.expander.enabled = value;
            }
        }
        Message::Expander(Expander::Attack(mode, value)) => {
            if processor_mode_from_expander(mode) == dsp.expander.mode {
                dsp.expander.attack_ms = value.to_inner();
            }
        }
        Message::Expander(Expander::Release(mode, value)) => {
            if processor_mode_from_expander(mode) == dsp.expander.mode {
                dsp.expander.release_ms = value.to_inner();
            }
        }
        Message::Suppressor(Suppressor::Enabled(value)) => dsp.suppressor.enabled = value,
        Message::Suppressor(Suppressor::Amount(value)) => {
            dsp.suppressor.amount = value.to_inner();
        }
        Message::Suppressor(Suppressor::Style(value)) => {
            dsp.suppressor.style = noise_style(value);
        }
        Message::Suppressor(Suppressor::Sensitivity(value)) => {
            dsp.suppressor.sensitivity_db = value.to_inner();
        }
        Message::Suppressor(Suppressor::AdaptTime(value)) => {
            dsp.suppressor.adapt_ms = value.to_inner();
        }
        Message::DeEsser(DeEsser::Amount(value)) => dsp.de_esser.amount = value.to_inner(),
        Message::DeEsser(DeEsser::Enabled(value)) => dsp.de_esser.enabled = value,
        Message::Exciter(Exciter::Amount(value)) => dsp.exciter.amount = value.to_inner(),
        Message::Exciter(Exciter::Frequency(value)) => {
            // The local v0.1.x DSP model exposes this as a normalized Tone control.
            // Preserve the hardware frequency monotonically until the model gains a native Hz field.
            let hz = value.to_inner();
            dsp.exciter.tone = ((hz - 600.0) / 4_400.0 * 100.0).clamp(0.0, 100.0);
        }
        Message::Exciter(Exciter::Enabled(value)) => dsp.exciter.enabled = value,
        Message::Headphones(Headphones::HeadphoneLevel(value)) => {
            dsp.headphones.level_db = value.to_inner();
        }
        Message::Headphones(Headphones::MicMonitor(value)) => {
            dsp.headphones.mic_monitor_db = value.to_inner();
        }
        Message::Headphones(Headphones::MicOutputGain(value)) => {
            dsp.mic_output_gain_db = value.to_inner();
        }
        Message::Headphones(Headphones::HeadphoneType(value)) => {
            dsp.headphones.power = headphone_power(value);
        }
        Message::Headphones(Headphones::FXEnabled(value)) => dsp.headphones.fx_enabled = value,
        Message::Controls(Controls::Mono(value)) => dsp.headphones.mono = value,
        Message::Controls(Controls::Balance(value)) => dsp.headphones.balance = value.to_inner(),
        Message::EQHeadphones(EQHeadphones::Linked(value)) => dsp.headphones.eq_linked = value,
        Message::EQHeadphones(EQHeadphones::Type(channel, band, value)) => {
            if let Some(slot) = headphone_band_mut(dsp, channel, band) {
                slot.kind = eq_kind(value);
            }
        }
        Message::EQHeadphones(EQHeadphones::Gain(channel, band, value)) => {
            if let Some(slot) = headphone_band_mut(dsp, channel, band) {
                slot.gain_db = value.to_inner();
            }
        }
        Message::EQHeadphones(EQHeadphones::Frequency(channel, band, value)) => {
            if let Some(slot) = headphone_band_mut(dsp, channel, band) {
                slot.frequency_hz = value.to_inner();
            }
        }
        Message::EQHeadphones(EQHeadphones::Q(channel, band, value)) => {
            if let Some(slot) = headphone_band_mut(dsp, channel, band) {
                slot.q = value.to_inner();
            }
        }
        Message::EQHeadphones(EQHeadphones::Enabled(channel, band, value)) => {
            if let Some(slot) = headphone_band_mut(dsp, channel, band) {
                slot.enabled = value;
            }
        }
        _ => return false,
    }
    true
}

fn headphone_band_mut(
    dsp: &mut SoftwareDspState,
    channel: EQChannel,
    band: EQBand,
) -> Option<&mut crate::hardware::EqBandState> {
    let index = eq_index(band);
    match channel {
        EQChannel::Left => dsp.headphones.eq_left.get_mut(index),
        EQChannel::Right => dsp.headphones.eq_right.get_mut(index),
    }
}

const fn eq_index(band: EQBand) -> usize {
    band as usize
}

const fn processor_mode_from_eq(value: EQMode) -> ProcessorMode {
    match value {
        EQMode::Simple => ProcessorMode::Simple,
        EQMode::Advanced => ProcessorMode::Advanced,
    }
}

const fn processor_mode_from_compressor(value: CompressorMode) -> ProcessorMode {
    match value {
        CompressorMode::Simple => ProcessorMode::Simple,
        CompressorMode::Advanced => ProcessorMode::Advanced,
    }
}

const fn processor_mode_from_expander(value: ExpanderMode) -> ProcessorMode {
    match value {
        ExpanderMode::Simple => ProcessorMode::Simple,
        ExpanderMode::Advanced => ProcessorMode::Advanced,
    }
}

const fn eq_kind(value: EQBandType) -> EqBandKind {
    match value {
        EQBandType::NotSet => EqBandKind::NotSet,
        EQBandType::LowPassFilter => EqBandKind::LowPass,
        EQBandType::HighPassFilter => EqBandKind::HighPass,
        EQBandType::NotchFilter => EqBandKind::Notch,
        EQBandType::BellBand => EqBandKind::Bell,
        EQBandType::LowShelf => EqBandKind::LowShelf,
        EQBandType::HighShelf => EqBandKind::HighShelf,
    }
}

const fn noise_style(value: SuppressorStyle) -> NoiseStyle {
    match value {
        SuppressorStyle::Instant => NoiseStyle::Instant,
        SuppressorStyle::Adaptive => NoiseStyle::Adaptive,
        SuppressorStyle::Snapshot => NoiseStyle::Snapshot,
    }
}

const fn headphone_power(value: HeadphoneTypes) -> HeadphonePower {
    match value {
        HeadphoneTypes::LineLevel => HeadphonePower::LineLevel,
        HeadphoneTypes::NormalPower => HeadphonePower::Normal,
        HeadphoneTypes::HighImpedance => HeadphonePower::HighImpedance,
        HeadphoneTypes::InEarMonitors => HeadphonePower::InEarMonitors,
    }
}

fn cache_dir() -> io::Result<PathBuf> {
    let home = env::var_os("HOME")
        .map(PathBuf::from)
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "HOME is not set"))?;
    Ok(home.join(".config/aetherforge-beacn-control/on-device"))
}

fn newest_profile(dir: &Path) -> io::Result<PathBuf> {
    let mut candidates = Vec::new();
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|value| value.to_str()) != Some("profile") {
            continue;
        }
        let modified = entry.metadata()?.modified()?;
        candidates.push((modified, path));
    }
    candidates
        .into_iter()
        .max_by_key(|(modified, _)| *modified)
        .map(|(_, path)| path)
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "no onboard-profile cache exists"))
}

fn atomic_write(path: &Path, contents: &str) -> io::Result<()> {
    let tmp = path.with_extension("tmp");
    fs::write(&tmp, contents)?;
    fs::rename(tmp, path)
}

fn serial_matches(device_serial: &str, requested: &str) -> bool {
    let device = device_serial.trim().to_ascii_lowercase();
    let requested = requested.trim().to_ascii_lowercase();
    device == requested || device.ends_with(&requested) || requested.ends_with(&device)
}

fn safe_serial(serial: &str) -> String {
    let filtered: String = serial
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || matches!(ch, '-' | '_') {
                ch
            } else {
                '_'
            }
        })
        .collect();
    if filtered.is_empty() {
        "beacn-mic".to_owned()
    } else {
        filtered
    }
}

fn clean_meta(value: &str) -> String {
    value.replace(['\n', '\r'], " ")
}

fn meta_field(text: &str, key: &str) -> Option<String> {
    let prefix = format!("{key}=");
    text.lines()
        .find_map(|line| line.strip_prefix(&prefix))
        .map(ToOwned::to_owned)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cache_serial_is_filesystem_safe() {
        assert_eq!(safe_serial("BEACN/ABC:123"), "BEACN_ABC_123");
    }

    #[test]
    fn eq_band_index_fits_local_model() {
        assert!(eq_index(EQBand::Band9) < crate::software_dsp::MIC_EQ_BAND_COUNT);
    }

    #[test]
    fn serial_matching_accepts_prefixed_linux_identity() {
        assert!(serial_matches(
            "BEACN_BEACN_Mic_0011240700359B",
            "0011240700359B"
        ));
    }
}
