[workspace]
members = [
  "crates/forgehx-core",
  "crates/forgehx-device",
  "crates/forgehx-mouse",
  "crates/forgehx-mic",
  "crates/forgehx-keyboard",
  "crates/forgehx-firmware",
  "crates/forgehx-audio",
  "crates/forgehx-aetherstream",
  "crates/forgehx-dsp",
  "crates/forgehx-backends",
  "crates/forgehx-daemon",
  "crates/forgehx-ipc",
  "crates/forgehx-cli",
  "crates/forgehx-gui",
  "crates/forgehx-tray",
]
resolver = "2"

[workspace.package]
version = "10.0.31"
edition = "2021"
license = "MIT"
authors = ["ForgeHX contributors"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
sha2 = "0.10"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "time", "signal", "fs", "sync"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
hidapi = { version = "2", default-features = false, features = ["linux-native"] }
eframe = { version = "0.33.3", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
sonora = "0.2"
pipewire = { version = "0.10.1", features = ["v0_3_41"] }
