#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ORG="$ROOT/src/organizer.rs"
TEST="$ROOT/tests/organizer.rs"

grep -Fq 'pub struct BuildIdentity' "$ORG"
grep -Fq 'pub fn build_identity_from_entry' "$ORG"
grep -Fq 'pub fn project_builds' "$ORG"
grep -Fq 'pub fn project_build(' "$ORG"
grep -Fq 'BUILD_ARTIFACT_ROUTED=' "$ORG"
grep -Fq 'create_build_artifact_alias' "$ORG"
grep -Fq 'Category::Installers' "$ORG"
grep -Fq '"sh" | "bash" | "fish" | "run"' "$ORG"
grep -Fq 'organizer_groups_build_bundle_and_leaves_legacy_aliases' "$TEST"
grep -Fq 'parses_build_identity_across_aetherforge_artifact_names' "$TEST"
grep -Fq 'pub fn legacy_build_artifact_candidates' "$ORG"
grep -Fq 'reconcile_existing_build_artifacts' "$ORG"
grep -Fq 'organizer_reconciles_existing_legacy_buckets_into_project_builds' "$TEST"
grep -Fq 'organizer_continuously_reconciles_new_artifacts_in_legacy_project_areas' "$TEST"
grep -Fq 'incomplete_downloads_never_become_build_artifacts' "$TEST"
grep -Fq 'lower.ends_with(".part")' "$ORG"
grep -Fq 'lower.ends_with(".partial")' "$ORG"
grep -Fq 'lower.ends_with(".tmp")' "$ORG"
echo FORGECLEAN_V0_5_2_BUILD_AWARE=PASS
