#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
GC="$ROOT/src/coldpack_gc.rs"
MAIN="$ROOT/src/main.rs"
COLD="$ROOT/src/coldstore.rs"
LIB="$ROOT/src/lib.rs"
SERVICE="$ROOT/forgeclean-organizer.service.in"

[[ -f "$GC" ]]
grep -Fq 'pub const QUARANTINE_SECONDS: u64 = 7 * 24 * 60 * 60;' "$GC"
grep -Fq 'pub fn coldpack_status' "$GC"
grep -Fq 'pub fn coldpack_audit' "$GC"
grep -Fq 'pub fn coldpack_gc_preview' "$GC"
grep -Fq 'pub fn coldpack_gc_apply' "$GC"
grep -Fq 'lock_store_exclusive' "$GC"
grep -Fq 'lock_store_shared' "$GC"
grep -Fq 'pub mod coldpack_gc;' "$LIB"
grep -Fq 'lock_store_exclusive(store_dir)?' "$COLD"
grep -Fq 'lock_store_shared(store_dir)?' "$COLD"
grep -Fq '"coldpack-status"' "$MAIN"
grep -Fq '"coldpack-audit"' "$MAIN"
grep -Fq '"coldpack-gc"' "$MAIN"
grep -Fq 'coldpack_maintenance_hours' "$ROOT/src/gui_state.rs"
grep -Fq 'pub const DEFAULT_MAINTENANCE_HOURS: u64 = 24;' "$ROOT/src/gui_state.rs"
grep -Fq 'coldpack_gc_apply' "$MAIN"
grep -Fq 'FORGECLEAN_COLDPACK_MAINTENANCE=' "$MAIN"
grep -Fq 'settings.coldpack_maintenance_enabled' "$MAIN"
grep -Fq 'ExecStart=%h/.local/bin/forgeclean watch' "$SERVICE"
grep -Fq 'pub const DEFAULT_STABLE_SECONDS: u64 = 30;' "$ROOT/src/gui_state.rs"
grep -Fq 'pub const DEFAULT_POLL_SECONDS: u64 = 2;' "$ROOT/src/gui_state.rs"
printf 'FORGECLEAN_V0_5_0_REGRESSION=PASS\n'
